### PR TITLE
catalog grid

### PR DESCRIPTION
**Pull request by Uktam19980416**
- [DEMO LINK](https://Uktam19980416.github.io/layout_catalog_grid/)

### CODE REVIEW

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
Please, do not add package-lock.json to the commit. This has been mentioned many times
Remove it.
Also the cards seem to be too far apart

**Review by meforoma — CHANGES_REQUESTED** [review]
come on, deploy the code. The only active deployment is 22 days old
Deployments

**Comment by Uktam19980416** [comment]
[DEMO LINK](https://Uktam19980416.github.io/layout_catalog_grid/)

**Comment by Uktam19980416** [comment]
> come on, deploy the code. The only active deployment is 22 days old Deployments

**Pull request closed without merging**
