### PR TITLE
first

### PR DESCRIPTION
**Pull request by Artem18084**
- [DEMO LINK](https://Artem18084.github.io/layout_catalog_grid/)

### CODE REVIEW

**Review by olena1994 — APPROVED** [review]
Good job!

**Review by VinnieJ-2k20 — CHANGES_REQUESTED** [review]
Layout works correctly, but card itself is broken
image

**Comment by Artem18084** [comment]
- [DEMO LINK](https://Artem18084.github.io/layout_catalog_grid/)

**Review by VinnieJ-2k20 — APPROVED** [review]
Good job 👍

**Pull request closed without merging**
